service: product-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - {"Fn::GetAtt": ["ProductsTable", "Arn"]}
            - {"Fn::GetAtt": ["StockTable", "Arn"]}
  httpApi:
    cors:
      allowedOrigins:
        - '*'

package:
  exclude:
    - ./**
  include:
    - build/**

custom:
  prune:
    automatic: true

functions:
  getProducts:
    handler: build/bundle.getProducts
    events:
     - httpApi:
        path: /products
        method: get
  getProduct:
    handler: build/bundle.getProduct
    events:
     - httpApi:
        path: /products/{productId}
        method: get
  createProduct:
    handler: build/bundle.createProduct
    events:
     - httpApi:
        path: /products
        method: post

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ProductsTable
      DependsOn: StockTable
      DeletionPolicy: Retain

    StockTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: StockTable

plugins:
  - serverless-prune-versions
